#!/bin/bash

# make sure all is up to date
sudo apt-get update -y
sudo apt-get upgrade -y

# prereqs
sudo apt install gtk2-engines-murrine sassc gnome-themes-extra -y

# install the GTK theme
sudo mkdir -p ~/.config/gtk-3.0
sudo mkdir -p ~/.config/gtk-4.0
sudo cp -r ./gtk/gtk-3.0/* ~/.config/gtk-3.0
sudo cp -r ./gtk/gtk-4.0/* ~/.config/gtk-4.0

# backup old conf
mkdir -p ./backup
dconf dump / > ./backup/dconf-settings-backup.ini

# gnome config (including extensions)
dconf load / < ./config/dconf-settings.ini
