#!/bin/bash

# basic libs
sudo apt-get install -y
	git \
	curl \
	neovim

# install vim plug
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# copy vim config
sudo cp ./config/.vimrc ~

# gnome
sudo apt-get install -y
	libxss1 \
	libappindicator1 \
	libindicator7 \
	gnome-tweaks \
	gnome-shell-extension-manager \

# terminal stuff
sudo apt install -y \
	tilix \
	cmatrix \
	cbonsai

sudo mkdir ~/.config/tilix
sudo cp config/tilix-session.json ~/.config/tilix/

# executables / helper scripts
sudo cp -r bin ~/