#!/bin/bash

# make sure all is up to date
sudo apt-get update -y
sudo apt-get upgrade -y

# install zsh
sudo apt install zsh -y

# install oh my zsh
sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

# install welcome message deps
sudo apt install lolcat fortune cowsay -y

# move config files
./install-terminal-configs

# install fonts
sudo cp -r ./powerlevel10k-fonts /usr/share/fonts
fc-cache -f -v

# install the theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
sed -i 's#^ZSH_THEME="[^"]*"#ZSH_THEME="powerlevel10k/powerlevel10k"#' ~/.zshrc

# install auto suggestion plugin
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# set zsh as default shell
sudo chsh -s $(which zsh)
